---
title: "P8105_hw3_zf2211"
author: "Francis"
date: "10/10/2018"
output: github_document
---
```{r}
library(tidyverse)
```

#Problem 1

```{r}
#read data
library(p8105.datasets)
data(brfss_smart2010, package = "p8105.datasets")
```

```{r}
#tidy up data
brfss = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = as_factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"), ordered = TRUE))
```

In 2002, states
```{r}
brfss %>% 
  filter(year == "2002") %>% 
  distinct(locationabbr, locationdesc) %>% 
  count(locationabbr) %>% 
  filter(n == 7)
```
were observed at 7 locations.


```{r}
#create a dataset for spaghetti plot
brfss1 = brfss %>% 
  group_by(locationabbr, year) %>% 
  distinct(locationdesc) %>% 
  count(locationabbr)
```

```{r}
#spaghetti plot
ggplot(brfss1, aes(x = year, y = n, color = locationabbr)) +
  geom_line() +
  geom_point()
```
This spaghetti plot shows the number of locations change in each state from 2002 to 2010. As we can see, most states have the similar trend and the change is relatively small, while FL had big fluctuation in 2007 and 2010.


#Problem2

```{r}
data(instacart, package = "p8105.datasets")
#read data
```


#Problem3

```{r}
data(ny_noaa, package = "p8105.datasets")
#read data
```

